import { SportConfig } from "./types";

export const SPORTS_CONFIG: Record<string, SportConfig> = {
  chess: {
    id: "chess",
    name: "Chess (Singles)",
    type: "individual",
    mainPlayers: 1,
    substitutes: 0,
    minSubstitutes: 0,
    category: "Indoor",
    iconName: "Crown",
    emoji: "♟️",
  },
  table_tennis: {
    id: "table_tennis",
    name: "Table Tennis (Singles)",
    type: "individual",
    mainPlayers: 1,
    substitutes: 0,
    minSubstitutes: 0,
    category: "Racket",
    iconName: "Disc",
    emoji: "🏓",
  },
  badminton_doubles: {
    id: "badminton_doubles",
    name: "Badminton (Doubles)",
    type: "doubles",
    mainPlayers: 2,
    substitutes: 0,
    minSubstitutes: 0,
    category: "Racket",
    iconName: "Users",
    emoji: "🏸",
  },
  basketball: {
    id: "basketball",
    name: "Basketball (5 Players)",
    type: "team",
    mainPlayers: 5,
    substitutes: 3,
    minSubstitutes: 1,
    category: "Court",
    iconName: "Flame",
    emoji: "🏀",
  },
  volleyball: {
    id: "volleyball",
    name: "Volleyball (6 Players)",
    type: "team",
    mainPlayers: 6,
    substitutes: 3,
    minSubstitutes: 1,
    category: "Outdoor",
    iconName: "Sun",
    emoji: "🏐",
  },
  football: {
    id: "football",
    name: "Football (11 Players)",
    type: "team",
    mainPlayers: 11,
    substitutes: 3,
    minSubstitutes: 1,
    category: "Outdoor",
    iconName: "Shield",
    emoji: "⚽",
  },
  cricket: {
    id: "cricket",
    name: "Cricket (11 Players)",
    type: "team",
    mainPlayers: 11,
    substitutes: 3,
    minSubstitutes: 1,
    category: "Outdoor",
    iconName: "Trophy",
    emoji: "🏏",
  },
  kho_kho: {
    id: "kho_kho",
    name: "Kho-Kho (10 Players)",
    type: "team",
    mainPlayers: 10,
    substitutes: 3,
    minSubstitutes: 1,
    category: "Outdoor",
    iconName: "Users",
    emoji: "🤸",
  },
  tug_of_war: {
    id: "tug_of_war",
    name: "Tug Of War (8 Players)",
    type: "team",
    mainPlayers: 8,
    substitutes: 3,
    minSubstitutes: 1,
    category: "Outdoor",
    iconName: "Users",
    emoji: "💪",
  },
  relay_race: {
    id: "relay_race",
    name: "Relay Race (4 Players)",
    type: "team",
    mainPlayers: 4,
    substitutes: 3,
    minSubstitutes: 1,
    category: "Track",
    iconName: "Zap",
    emoji: "🏃",
  },
  seven_stones: {
    id: "seven_stones",
    name: "7 Stones (7 Players)",
    type: "team",
    mainPlayers: 7,
    substitutes: 3,
    minSubstitutes: 1,
    category: "Outdoor",
    iconName: "Layers",
    emoji: "🪨",
  },
  kabaddi: {
    id: "kabaddi",
    name: "Kabaddi (7 Players)",
    type: "team",
    mainPlayers: 7,
    substitutes: 3,
    minSubstitutes: 1,
    category: "Outdoor",
    iconName: "Shield",
    emoji: "🤼",
  },
  athletics_100m: {
    id: "athletics_100m",
    name: "Athletics (100m Sprint)",
    type: "individual",
    mainPlayers: 1,
    substitutes: 0,
    minSubstitutes: 0,
    category: "Track",
    iconName: "Zap",
    emoji: "🏃",
  },
  athletics_200m: {
    id: "athletics_200m",
    name: "Athletics (200m Sprint)",
    type: "individual",
    mainPlayers: 1,
    substitutes: 0,
    minSubstitutes: 0,
    category: "Track",
    iconName: "Zap",
    emoji: "🏃",
  },
  athletics_400m: {
    id: "athletics_400m",
    name: "Athletics (400m)",
    type: "individual",
    mainPlayers: 1,
    substitutes: 0,
    minSubstitutes: 0,
    category: "Track",
    iconName: "Zap",
    emoji: "🏃",
  },
  long_jump: {
    id: "long_jump",
    name: "Long Jump",
    type: "individual",
    mainPlayers: 1,
    substitutes: 0,
    minSubstitutes: 0,
    category: "Track",
    iconName: "ArrowRight",
    emoji: "🦘",
  },
  high_jump: {
    id: "high_jump",
    name: "High Jump",
    type: "individual",
    mainPlayers: 1,
    substitutes: 0,
    minSubstitutes: 0,
    category: "Track",
    iconName: "ArrowUp",
    emoji: "🏋️",
  },
  shot_put: {
    id: "shot_put",
    name: "Shot Put",
    type: "individual",
    mainPlayers: 1,
    substitutes: 0,
    minSubstitutes: 0,
    category: "Track",
    iconName: "Circle",
    emoji: "⚾",
  },
  discus_throw: {
    id: "discus_throw",
    name: "Discus Throw",
    type: "individual",
    mainPlayers: 1,
    substitutes: 0,
    minSubstitutes: 0,
    category: "Track",
    iconName: "Circle",
    emoji: "🥏",
  },
  javelin_throw: {
    id: "javelin_throw",
    name: "Javelin Throw",
    type: "individual",
    mainPlayers: 1,
    substitutes: 0,
    minSubstitutes: 0,
    category: "Track",
    iconName: "ArrowRight",
    emoji: "🎯",
  },
};
