import { SportConfig } from "./types";

export const SPORTS_CONFIG: Record<string, SportConfig> = {
  chess_singles: {
    id: "chess_singles",
    name: "Chess (Singles)",
    type: "individual",
    mainPlayers: 1,
    substitutes: 0,
    minSubstitutes: 0,
    category: "Indoor",
    iconName: "Crown",
  },
  badminton_singles: {
    id: "badminton_singles",
    name: "Badminton (Singles)",
    type: "individual",
    mainPlayers: 1,
    substitutes: 0,
    minSubstitutes: 0,
    category: "Racket",
    iconName: "Activity",
  },
  table_tennis_singles: {
    id: "table_tennis_singles",
    name: "Table Tennis (Singles)",
    type: "individual",
    mainPlayers: 1,
    substitutes: 0,
    minSubstitutes: 0,
    category: "Racket",
    iconName: "Disc",
  },
  athletics_100m: {
    id: "athletics_100m",
    name: "Athletics (100m Sprint)",
    type: "individual",
    mainPlayers: 1,
    substitutes: 0,
    minSubstitutes: 0,
    category: "Track",
    iconName: "Zap",
  },

  chess_doubles: {
    id: "chess_doubles",
    name: "Chess (Doubles)",
    type: "doubles",
    mainPlayers: 2,
    substitutes: 0,
    minSubstitutes: 0,
    category: "Indoor",
    iconName: "Users",
  },
  badminton_doubles: {
    id: "badminton_doubles",
    name: "Badminton (Doubles)",
    type: "doubles",
    mainPlayers: 2,
    substitutes: 0,
    minSubstitutes: 0,
    category: "Racket",
    iconName: "Users",
  },
  table_tennis_doubles: {
    id: "table_tennis_doubles",
    name: "Table Tennis (Doubles)",
    type: "doubles",
    mainPlayers: 2,
    substitutes: 0,
    minSubstitutes: 0,
    category: "Racket",
    iconName: "Users",
  },

  football: {
    id: "football",
    name: "Football",
    type: "team",
    mainPlayers: 11,
    substitutes: 3,
    minSubstitutes: 1,
    category: "Outdoor",
    iconName: "Shield",
  },
  volleyball: {
    id: "volleyball",
    name: "Volleyball",
    type: "team",
    mainPlayers: 7,
    substitutes: 3,
    minSubstitutes: 1,
    category: "Outdoor",
    iconName: "Sun",
  },
  basketball: {
    id: "basketball",
    name: "Basketball",
    type: "team",
    mainPlayers: 5,
    substitutes: 3,
    minSubstitutes: 1,
    category: "Court",
    iconName: "Flame",
  },
  cricket: {
    id: "cricket",
    name: "Cricket",
    type: "team",
    mainPlayers: 11,
    substitutes: 3,
    minSubstitutes: 1,
    category: "Outdoor",
    iconName: "Trophy",
  },
  kabaddi: {
    id: "kabaddi",
    name: "Kabaddi",
    type: "team",
    mainPlayers: 7,
    substitutes: 3,
    minSubstitutes: 1,
    category: "Outdoor",
    iconName: "Users",
  },
};
